## ART

In [1]:
import numpy as np

In [65]:
X = np.array([[0, 0, 0, 1], [0, 1, 0, 1], [0, 0, 1, 1], [1, 0, 0, 0]])

In [66]:
X

array([[0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [1, 0, 0, 0]])

In [67]:
rho = 0.4
alpha = 2
n = 4
m = 3

In [68]:
bottom = 1/(1+n)

In [69]:
bottom

0.2

In [70]:
def weights(n, m, value):
    weight = []
    for i in range(n):
        temp = []
        for j in range(m):
            temp.append(value)
        weight.append(temp)
    return weight

In [71]:
bij = np.array(weights(n, m, bottom))

In [72]:
bij

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [73]:
tji = np.array(weights(m, n, 1))

In [74]:
tji

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
s = X[0]

In [76]:
def norm(s):
    norm_s = 0
    for i in s:
        norm_s+=i
    return norm_s

In [77]:
norm_s = norm(s)

In [78]:
norm_s

1

In [79]:
norm_x = norm(X[0])

In [80]:
norm_x

1

In [81]:
def aggregation(n, bij, x):
    for i in range(n):
        yi = bij[i]*x[i]
    return yi

In [82]:
bij_T = bij.T

In [83]:
print(aggregation(n, bij_T[0], X[0]))

0.2


In [84]:
Y = []
for i in range(m):
    Y.append(aggregation(n, bij_T[i], X[0]))

In [85]:
print (Y)

[0.2, 0.2, 0.2]


In [86]:
min_y = Y[0]
j = 0
for i in range(len(Y)):
    if min_y>Y[i]:
        min_y = Y[i]
        value = i

In [87]:
min_y

0.2

In [88]:
j

0

In [89]:
xi = s*tji[j][0]

In [90]:
xi

array([0, 0, 0, 1])

In [91]:
norm_xi = norm(xi)

In [92]:
norm_xi

1

In [93]:
value = norm_xi/norm_s

In [94]:
value

1.0

In [95]:
if value>rho:
    bij_new = (alpha*xi)/((alpha - 1) +(norm_xi))

In [96]:
bij_new

array([0., 0., 0., 1.])

In [97]:
bij_T[0] = bij_new

In [98]:
bij_T

array([[0. , 0. , 0. , 1. ],
       [0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2]])

In [99]:
tji[0] = bij_new

In [100]:
tji

array([[0, 0, 0, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [101]:
# tji cha first row update zala bij sarkha 